spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    username: serveruser
    password: serverpass
logging:
  level:
    ee:
      avalanchelabs: debug