version: "2.1"

services:
  wallet-server:
    image: ee.avalanchelabs/wallet-server:1.0
    container_name: wallet-server
    ports:
      - 9090:9090
    environment:
      - WALLET_SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/wallet
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_PLATFORM=mysql
      - SPRING_DATASOURCE_USERNAME=serveruser
      - SPRING_DATASOURCE_PASSWORD=serverpass
    depends_on:
      mysql5:
        condition: service_healthy
    networks:
      wallet-network:
        aliases:
          - wallet-server
  mysql5:
    image: mysql:5.7
    container_name: mysql5
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=wallet
      - MYSQL_USER=serveruser
      - MYSQL_PASSWORD=serverpass
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    healthcheck:
      test: ["CMD", "mysqladmin", "--password=root" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      wallet-network:
        aliases:
          - db
networks:
  wallet-network:
    name: wallet-network
volumes:
  mysql-data: